######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 5 17:30:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h PCAPlayer.h
SOURCES += main.cpp MainWindow.cpp PCAPlayer.cpp


unix {
    CONFIG += link_pkgconfig
    PKGCONFIG += opencv
}
